# Generated by Django 5.1.6 on 2025-02-19 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="band",
            name="biograpphy",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                    ("RG", "Reggae"),
                    ("CT", "Country"),
                ],
                default="HH",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="band",
            name="official_homepage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="band",
            name="year_formed",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2021),
                ],
            ),
            preserve_default=False,
        ),
    ]
