# Generated by Django 5.1.6 on 2025-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
    ]
