# Generated by Django 5.1.6 on 2025-02-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_band_like_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="like_new",
        ),
    ]
